version: '3.5'

services:

  postgres:
    container_name: postgres_db
    image: postgres
    networks:
      - ecosystem_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

  # neo4j container with apoc
  neo4j:
    container_name: neo4j_db
    image: neo4j:4.4.5
    networks:
      - ecosystem_network
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/passw0rd
      NEO4J_dbms_connector_bolt_enabled: "true"
      NEO4JLABS_apoc_export_file_enabled: "true"
      NEO4JLABS_apoc_import_file_enabled: "true"
      NEO4JLABS_apoc_import_file_use__neo4j__config: "true"
    volumes:
      - ./neo4j/plugins:/plugins
    restart: always


  backend:
    container_name: backend
    build: ./backend
    networks:
      - ecosystem_network
    ports:
      - '8080:8080'
    links:
      - "neo4j"
    depends_on:
      - "postgres"
      - "neo4j"

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - ecosystem_network
    ports:
      - '4173:4173'
    depends_on:
      - "backend"

  nginx:
    container_name: nginx
    image: proxy
    build: ./.nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"

networks:
    ecosystem_network:
      driver: bridge

